name: CI
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: 84codes/crystal:latest-ubuntu-26.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Checkout ameba
        uses: actions/checkout@v6
        with:
          repository: crystal-ameba/ameba
          path: ameba
      - name: Compile ameba
        run: make -C ameba
      - name: Lint
        run: ameba/bin/ameba src

  spec:
    name: Spec
    runs-on: ubuntu-latest
    container: 84codes/crystal:latest-ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
      - run: shards install
      - run: crystal spec --order random -Dpreview_mt -Dexecution_context

  format:
    name: Formatting
    runs-on: ubuntu-latest
    container: 84codes/crystal:latest-ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Format check
        run: crystal tool format --check
